baseURL = "http://blog.5000164.jp"
DefaultContentLanguage = "ja"
hasCJKLanguage = true
languageCode = "ja"
title = "5000164 is here"
theme = "divided"
publishDir = "docs"

pygmentsUseClassic = true
pygmentscodefences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsStyle = "monokai"
pygmentsUseClasses = true
pygmentsoptions = "linenos=on"

googleAnalytics = "UA-51024599-1"
