baseURL = "http://blog.5000164.jp/"
DefaultContentLanguage = "ja"
hasCJKLanguage = true
languageCode = "ja"
title = "5000164 is here"
theme = "remember"
publishDir = "docs"
summaryLength = 400
pluralizeListTitles = false

pygmentsOptions = "linenos=table"
pygmentscodefences = true
pygmentsStyle = "monokai"
pygmentsCodefencesGuessSyntax = true

googleAnalytics = "UA-51024599-1"

[Params]
description = "菅原 浩 のブログ"
icon = "icon.png"
twitter_card = "summary"
twitter_site = "@5000164"
twitter_creator = "@5000164"
